import {
  Patient,
  LiveSensorData,
  ClinicalInputData,
  AIAnalysisData,
  DeteriorationData,
  ExplainableRiskData,
  ClinicalAlert,
  Doctor,
  OverviewMetrics,
} from '../types';

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'DOC-01',
    name: 'Dr. Sarah Lin, MD',
    department: 'Critical Care / ICU',
    specialization: 'Intensivist & Hemodynamics',
    activeCases: 4,
    activeAlerts: 2,
    email: 's.lin@vitaguard-hospital.org',
    pager: '#4412',
    onCall: true,
    avatarInitials: 'SL',
  },
  {
    id: 'DOC-02',
    name: 'Dr. James Caldwell, MD',
    department: 'Cardiology',
    specialization: 'Arrhythmia & Interventional Cardiology',
    activeCases: 3,
    activeAlerts: 1,
    email: 'j.caldwell@vitaguard-hospital.org',
    pager: '#3381',
    onCall: true,
    avatarInitials: 'JC',
  },
  {
    id: 'DOC-03',
    name: 'Dr. Maya Patel, MD',
    department: 'Pulmonology',
    specialization: 'Acute Respiratory Failure & Ventilation',
    activeCases: 3,
    activeAlerts: 1,
    email: 'm.patel@vitaguard-hospital.org',
    pager: '#8820',
    onCall: false,
    avatarInitials: 'MP',
  },
  {
    id: 'DOC-04',
    name: 'Dr. Robert Sterling, MD',
    department: 'Emergency Medicine',
    specialization: 'Clinical Triage & Rapid Response',
    activeCases: 5,
    activeAlerts: 0,
    email: 'r.sterling@vitaguard-hospital.org',
    pager: '#9104',
    onCall: true,
    avatarInitials: 'RS',
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'PT-101',
    name: 'Arthur Pendelton',
    age: 68,
    gender: 'M',
    mrn: 'MRN-882910',
    ward: 'ICU Unit A',
    bed: 'Bed 04',
    currentRisk: 'CRITICAL',
    currentStatus: 'CRITICAL',
    assignedDoctor: 'Dr. Sarah Lin, MD',
    doctorId: 'DOC-01',
    department: 'Critical Care / ICU',
    admissionDate: '2026-08-25',
    primaryDiagnosis: 'Post-op Sepsis Syndrome / Severe Hypotension',
    lastUpdated: '1 min ago',
    notes: 'Under continuous arterial line and ESP32 telemetry node 01.',
  },
  {
    id: 'PT-102',
    name: 'Elena Rostova',
    age: 54,
    gender: 'F',
    mrn: 'MRN-674102',
    ward: 'Stepdown Ward C',
    bed: 'Bed 12',
    currentRisk: 'HIGH_RISK',
    currentStatus: 'DETERIORATING',
    assignedDoctor: 'Dr. James Caldwell, MD',
    doctorId: 'DOC-02',
    department: 'Cardiology',
    admissionDate: '2026-08-26',
    primaryDiagnosis: 'Post-CABG Paroxysmal Tachycardia & Hypoxemia',
    lastUpdated: '3 mins ago',
    notes: 'Heart rate escalating above baseline threshold. Telemetry Node 02.',
  },
  {
    id: 'PT-103',
    name: 'Marcus Vance',
    age: 42,
    gender: 'M',
    mrn: 'MRN-902188',
    ward: 'Pulmonary Ward B',
    bed: 'Bed 07',
    currentRisk: 'MONITORING',
    currentStatus: 'MONITORING',
    assignedDoctor: 'Dr. Maya Patel, MD',
    doctorId: 'DOC-03',
    department: 'Pulmonology',
    admissionDate: '2026-08-24',
    primaryDiagnosis: 'Exacerbated Viral Pneumonia / Mild Desaturation',
    lastUpdated: '5 mins ago',
    notes: 'Receiving 2L/min via nasal cannula. Monitoring SpO2 trends.',
  },
  {
    id: 'PT-104',
    name: 'Clara Higgins',
    age: 79,
    gender: 'F',
    mrn: 'MRN-334912',
    ward: 'Geriatric Med Ward',
    bed: 'Bed 19',
    currentRisk: 'HIGH_RISK',
    currentStatus: 'MONITORING',
    assignedDoctor: 'Dr. Robert Sterling, MD',
    doctorId: 'DOC-04',
    department: 'Emergency Medicine',
    admissionDate: '2026-08-26',
    primaryDiagnosis: 'Orthostatic Hypotension with High Fall Risk',
    lastUpdated: '2 mins ago',
    notes: 'IoT motion sensor active. Bed exit alarm engaged.',
  },
  {
    id: 'PT-105',
    name: 'David Chen',
    age: 35,
    gender: 'M',
    mrn: 'MRN-551093',
    ward: 'Surgical Recovery',
    bed: 'Bed 02',
    currentRisk: 'STABLE',
    currentStatus: 'STABLE',
    assignedDoctor: 'Dr. Sarah Lin, MD',
    doctorId: 'DOC-01',
    department: 'Critical Care / ICU',
    admissionDate: '2026-08-27',
    primaryDiagnosis: 'Laparoscopic Appendectomy (Post-Op Day 1)',
    lastUpdated: '8 mins ago',
    notes: 'Vital signs stable. Pain well controlled.',
  },
  {
    id: 'PT-106',
    name: 'Evelyn Brooks',
    age: 62,
    gender: 'F',
    mrn: 'MRN-449102',
    ward: 'Cardiology Telemetry',
    bed: 'Bed 08',
    currentRisk: 'HIGH_RISK',
    currentStatus: 'DETERIORATING',
    assignedDoctor: 'Dr. James Caldwell, MD',
    doctorId: 'DOC-02',
    department: 'Cardiology',
    admissionDate: '2026-08-26',
    primaryDiagnosis: 'Acute Coronary Syndrome Rule-Out / Hypertensive Urgency',
    lastUpdated: '4 mins ago',
    notes: 'Frequent premature ventricular contractions observed on ECG.',
  },
  {
    id: 'PT-107',
    name: 'Samuel Okafor',
    age: 51,
    gender: 'M',
    mrn: 'MRN-781190',
    ward: 'General Medicine',
    bed: 'Bed 15',
    currentRisk: 'STABLE',
    currentStatus: 'STABLE',
    assignedDoctor: 'Dr. Robert Sterling, MD',
    doctorId: 'DOC-04',
    department: 'Emergency Medicine',
    admissionDate: '2026-08-25',
    primaryDiagnosis: 'Cellulitis on IV Antibiotics',
    lastUpdated: '12 mins ago',
    notes: 'Afebrile, inflammatory markers trending downward.',
  },
  {
    id: 'PT-108',
    name: 'Beatrice Morales',
    age: 73,
    gender: 'F',
    mrn: 'MRN-190452',
    ward: 'ICU Unit B',
    bed: 'Bed 01',
    currentRisk: 'CRITICAL',
    currentStatus: 'CRITICAL',
    assignedDoctor: 'Dr. Maya Patel, MD',
    doctorId: 'DOC-03',
    department: 'Pulmonology',
    admissionDate: '2026-08-25',
    primaryDiagnosis: 'Acute Hypoxemic Respiratory Distress (ARDS)',
    lastUpdated: 'Just now',
    notes: 'High flow oxygen therapy. Escalation protocol triggered.',
  },
];

export const INITIAL_LIVE_SENSOR_DATA: Record<string, LiveSensorData> = {
  'PT-101': {
    patientId: 'PT-101',
    deviceId: 'ESP32-NODE-01A',
    heartRate: 126,
    spO2: 89,
    temperature: 39.2,
    ecgLead: 'Lead II',
    ecgSampleRateHz: 250,
    ecgRhythm: 'Sinus Tachycardia',
    motionStatus: 'AGITATED',
    fallDetected: false,
    deviceStatus: 'ONLINE',
    batteryLevel: 94,
    signalStrengthDbm: -58,
    latencyMs: 18,
    lastUpdated: '2026-08-27 08:02:14 UTC',
  },
  'PT-102': {
    patientId: 'PT-102',
    deviceId: 'ESP32-NODE-02B',
    heartRate: 118,
    spO2: 92,
    temperature: 37.9,
    ecgLead: 'Lead II',
    ecgSampleRateHz: 250,
    ecgRhythm: 'Atrial Fibrillation',
    motionStatus: 'RESTING',
    fallDetected: false,
    deviceStatus: 'ONLINE',
    batteryLevel: 88,
    signalStrengthDbm: -62,
    latencyMs: 24,
    lastUpdated: '2026-08-27 08:01:50 UTC',
  },
  'PT-103': {
    patientId: 'PT-103',
    deviceId: 'ESP32-NODE-03A',
    heartRate: 88,
    spO2: 94,
    temperature: 37.2,
    ecgLead: 'Lead II',
    ecgSampleRateHz: 250,
    ecgRhythm: 'Sinus Rhythm',
    motionStatus: 'BED_REST',
    fallDetected: false,
    deviceStatus: 'ONLINE',
    batteryLevel: 91,
    signalStrengthDbm: -55,
    latencyMs: 20,
    lastUpdated: '2026-08-27 07:59:12 UTC',
  },
  'PT-104': {
    patientId: 'PT-104',
    deviceId: 'ESP32-NODE-04C',
    heartRate: 76,
    spO2: 96,
    temperature: 36.8,
    ecgLead: 'Lead II',
    ecgSampleRateHz: 250,
    ecgRhythm: 'Sinus Rhythm',
    motionStatus: 'AGITATED',
    fallDetected: true,
    deviceStatus: 'ONLINE',
    batteryLevel: 76,
    signalStrengthDbm: -68,
    latencyMs: 31,
    lastUpdated: '2026-08-27 08:02:00 UTC',
  },
  'PT-105': {
    patientId: 'PT-105',
    deviceId: 'ESP32-NODE-05A',
    heartRate: 68,
    spO2: 99,
    temperature: 36.6,
    ecgLead: 'Lead II',
    ecgSampleRateHz: 250,
    ecgRhythm: 'Sinus Rhythm',
    motionStatus: 'RESTING',
    fallDetected: false,
    deviceStatus: 'ONLINE',
    batteryLevel: 98,
    signalStrengthDbm: -52,
    latencyMs: 16,
    lastUpdated: '2026-08-27 07:55:04 UTC',
  },
  'PT-106': {
    patientId: 'PT-106',
    deviceId: 'ESP32-NODE-06B',
    heartRate: 105,
    spO2: 92,
    temperature: 37.4,
    ecgLead: 'Lead II',
    ecgSampleRateHz: 250,
    ecgRhythm: 'Ventricular Ectopy',
    motionStatus: 'RESTING',
    fallDetected: false,
    deviceStatus: 'ONLINE',
    batteryLevel: 82,
    signalStrengthDbm: -64,
    latencyMs: 22,
    lastUpdated: '2026-08-27 08:00:30 UTC',
  },
  'PT-107': {
    patientId: 'PT-107',
    deviceId: 'ESP32-NODE-07A',
    heartRate: 72,
    spO2: 98,
    temperature: 36.7,
    ecgLead: 'Lead II',
    ecgSampleRateHz: 250,
    ecgRhythm: 'Sinus Rhythm',
    motionStatus: 'ACTIVE',
    fallDetected: false,
    deviceStatus: 'ONLINE',
    batteryLevel: 89,
    signalStrengthDbm: -59,
    latencyMs: 19,
    lastUpdated: '2026-08-27 07:52:10 UTC',
  },
  'PT-108': {
    patientId: 'PT-108',
    deviceId: 'ESP32-NODE-08C',
    heartRate: 134,
    spO2: 86,
    temperature: 38.7,
    ecgLead: 'Lead II',
    ecgSampleRateHz: 250,
    ecgRhythm: 'Sinus Tachycardia',
    motionStatus: 'AGITATED',
    fallDetected: false,
    deviceStatus: 'ONLINE',
    batteryLevel: 95,
    signalStrengthDbm: -50,
    latencyMs: 14,
    lastUpdated: '2026-08-27 08:02:22 UTC',
  },
};

export const INITIAL_CLINICAL_INPUTS: Record<string, ClinicalInputData> = {
  'PT-101': {
    patientId: 'PT-101',
    patientAge: 68,
    respiratoryRate: 28,
    systolicBP: 85,
    diastolicBP: 54,
    map: 64,
    avpuConsciousness: 'Verbal',
    supplementalO2LMin: 4.0,
    recordedBy: 'Nurse R. Martinez, RN',
    timestamp: '2026-08-27 08:00:00 UTC',
    clinicalNotes: 'Warm extremities, oliguria noted over previous 2 hours. Fluid bolus initiated.',
  },
  'PT-102': {
    patientId: 'PT-102',
    patientAge: 54,
    respiratoryRate: 22,
    systolicBP: 145,
    diastolicBP: 92,
    map: 110,
    avpuConsciousness: 'Alert',
    supplementalO2LMin: 2.0,
    recordedBy: 'Nurse J. Zhao, RN',
    timestamp: '2026-08-27 07:45:00 UTC',
    clinicalNotes: 'Palpitations reported following morning medication round.',
  },
  'PT-103': {
    patientId: 'PT-103',
    patientAge: 42,
    respiratoryRate: 20,
    systolicBP: 122,
    diastolicBP: 78,
    map: 93,
    avpuConsciousness: 'Alert',
    supplementalO2LMin: 2.0,
    recordedBy: 'Nurse K. Gallagher, RN',
    timestamp: '2026-08-27 07:30:00 UTC',
    clinicalNotes: 'Mild dyspnea upon ambulation, recovering on supplemental O2.',
  },
  'PT-104': {
    patientId: 'PT-104',
    patientAge: 79,
    respiratoryRate: 17,
    systolicBP: 104,
    diastolicBP: 66,
    map: 79,
    avpuConsciousness: 'Alert',
    supplementalO2LMin: 0,
    recordedBy: 'Nurse R. Martinez, RN',
    timestamp: '2026-08-27 07:50:00 UTC',
    clinicalNotes: 'Attempted unassisted bed egress; sensor triggered instant proximity notification.',
  },
  'PT-105': {
    patientId: 'PT-105',
    patientAge: 35,
    respiratoryRate: 14,
    systolicBP: 118,
    diastolicBP: 76,
    map: 90,
    avpuConsciousness: 'Alert',
    supplementalO2LMin: 0,
    recordedBy: 'Nurse S. Adams, RN',
    timestamp: '2026-08-27 07:15:00 UTC',
    clinicalNotes: 'Surgical wound clean and intact. Tolerating oral intake.',
  },
  'PT-106': {
    patientId: 'PT-106',
    patientAge: 62,
    respiratoryRate: 24,
    systolicBP: 160,
    diastolicBP: 98,
    map: 119,
    avpuConsciousness: 'Alert',
    supplementalO2LMin: 2.0,
    recordedBy: 'Nurse J. Zhao, RN',
    timestamp: '2026-08-27 07:40:00 UTC',
    clinicalNotes: 'Atypical sub-sternal chest discomfort. Serial troponin ordered.',
  },
  'PT-107': {
    patientId: 'PT-107',
    patientAge: 51,
    respiratoryRate: 15,
    systolicBP: 124,
    diastolicBP: 80,
    map: 95,
    avpuConsciousness: 'Alert',
    supplementalO2LMin: 0,
    recordedBy: 'Nurse S. Adams, RN',
    timestamp: '2026-08-27 07:00:00 UTC',
    clinicalNotes: 'Right lower extremity erythema resolving.',
  },
  'PT-108': {
    patientId: 'PT-108',
    patientAge: 73,
    respiratoryRate: 30,
    systolicBP: 90,
    diastolicBP: 60,
    map: 70,
    avpuConsciousness: 'Verbal',
    supplementalO2LMin: 6.0,
    recordedBy: 'Nurse R. Martinez, RN',
    timestamp: '2026-08-27 08:01:00 UTC',
    clinicalNotes: 'Labored breathing, accessory muscle use. Arterial blood gas sample sent.',
  },
};

export const INITIAL_AI_ANALYSIS: Record<string, AIAnalysisData> = {
  'PT-101': {
    patientId: 'PT-101',
    patientName: 'Arthur Pendelton',
    predictedCondition: 'Septic Shock / Hemodynamic Collapse',
    riskLevel: 'CRITICAL',
    confidence: 94.6,
    assignedDoctor: 'Dr. Sarah Lin, MD',
    department: 'Critical Care / ICU',
    analysisTimestamp: '2026-08-27 08:02:15 UTC',
    modelIdentifier: 'FastAPI Random Forest Clinical Risk v2.4 (Ensemble)',
    recommendedAction: 'Immediate ICU Senior Review: Administer 30 mL/kg crystalloid bolus, re-check serum lactate, and prepare norepinephrine infusion if MAP < 65 mmHg.',
    featureAttributions: [
      {
        feature: 'Body Temperature Elevation',
        clinicalValue: '39.2 °C',
        normalRange: '36.5 - 37.5 °C',
        importancePercent: 34.2,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'SpO2 Desaturation Trend',
        clinicalValue: '89 %',
        normalRange: '95 - 100 %',
        importancePercent: 28.5,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'Heart Rate (Sinus Tachycardia)',
        clinicalValue: '126 BPM',
        normalRange: '60 - 100 BPM',
        importancePercent: 21.1,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'Tachypnea (Respiratory Rate)',
        clinicalValue: '28 breaths/min',
        normalRange: '12 - 20 bpm',
        importancePercent: 11.4,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'Systolic Blood Pressure (Hypotension)',
        clinicalValue: '85 mmHg',
        normalRange: '100 - 130 mmHg',
        importancePercent: 4.8,
        impactDirection: 'ELEVATES_RISK',
      },
    ],
    clinicalRationale: 'Patient demonstrates classic systemic inflammatory response progression to septic shock with compounding hypoxemia and hyperpyrexia sustained over 45 minutes.',
  },
  'PT-102': {
    patientId: 'PT-102',
    patientName: 'Elena Rostova',
    predictedCondition: 'Post-Operative Atrial Fibrillation with Rapid Ventricular Response',
    riskLevel: 'HIGH_RISK',
    confidence: 88.2,
    assignedDoctor: 'Dr. James Caldwell, MD',
    department: 'Cardiology',
    analysisTimestamp: '2026-08-27 08:01:52 UTC',
    modelIdentifier: 'FastAPI Random Forest Clinical Risk v2.4 (Ensemble)',
    recommendedAction: 'Cardiology consult: 12-lead ECG verification, check serum electrolytes (K+, Mg2+), assess need for IV beta-blockade or amiodarone.',
    featureAttributions: [
      {
        feature: 'Heart Rate Spike',
        clinicalValue: '118 BPM',
        normalRange: '60 - 100 BPM',
        importancePercent: 42.0,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'SpO2 Mild Decline',
        clinicalValue: '92 %',
        normalRange: '95 - 100 %',
        importancePercent: 26.4,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'ECG Irregularity Score',
        clinicalValue: 'AFib pattern',
        normalRange: 'NSR',
        importancePercent: 18.2,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'Systolic Blood Pressure',
        clinicalValue: '145 mmHg',
        normalRange: '100 - 130 mmHg',
        importancePercent: 13.4,
        impactDirection: 'ELEVATES_RISK',
      },
    ],
    clinicalRationale: 'Sudden onset tachyarrhythmia with irregular R-R intervals on telemetry lead II causing mild reduction in peripheral perfusion.',
  },
  'PT-103': {
    patientId: 'PT-103',
    patientName: 'Marcus Vance',
    predictedCondition: 'Compensating Hypoxemic Viral Pneumonia',
    riskLevel: 'MONITORING',
    confidence: 82.1,
    assignedDoctor: 'Dr. Maya Patel, MD',
    department: 'Pulmonology',
    analysisTimestamp: '2026-08-27 07:59:15 UTC',
    modelIdentifier: 'FastAPI Random Forest Clinical Risk v2.4 (Ensemble)',
    recommendedAction: 'Continue current 2L nasal cannula oxygen therapy, repeat SpO2 trending every 30 minutes, maintain incentive spirometry.',
    featureAttributions: [
      {
        feature: 'SpO2 Borderline',
        clinicalValue: '94 %',
        normalRange: '95 - 100 %',
        importancePercent: 48.0,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'Respiratory Rate',
        clinicalValue: '20 breaths/min',
        normalRange: '12 - 20 bpm',
        importancePercent: 22.0,
        impactDirection: 'NORMAL',
      },
      {
        feature: 'Heart Rate',
        clinicalValue: '88 BPM',
        normalRange: '60 - 100 BPM',
        importancePercent: 18.0,
        impactDirection: 'NORMAL',
      },
      {
        feature: 'Temperature',
        clinicalValue: '37.2 °C',
        normalRange: '36.5 - 37.5 °C',
        importancePercent: 12.0,
        impactDirection: 'PROTECTIVE',
      },
    ],
    clinicalRationale: 'Patient exhibits stable physiological compensation under supplemental O2 without acute respiratory muscular fatigue.',
  },
  'PT-104': {
    patientId: 'PT-104',
    patientName: 'Clara Higgins',
    predictedCondition: 'Acute Motion / Fall Impact Event in Frail Patient',
    riskLevel: 'HIGH_RISK',
    confidence: 91.0,
    assignedDoctor: 'Dr. Robert Sterling, MD',
    department: 'Emergency Medicine',
    analysisTimestamp: '2026-08-27 08:02:02 UTC',
    modelIdentifier: 'FastAPI Random Forest Clinical Risk v2.4 (Ensemble)',
    recommendedAction: 'Urgent bedside nursing check: Verify physical safety, evaluate for head strike or orthopedic injury, assess orthostatic vitals.',
    featureAttributions: [
      {
        feature: 'IoT Accelerometer Impact Spike',
        clinicalValue: 'Fall Triggered (3.4G vector)',
        normalRange: '0.9 - 1.2G',
        importancePercent: 62.5,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'Agitated Motion State',
        clinicalValue: 'High frequency movement',
        normalRange: 'Resting',
        importancePercent: 21.0,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'Borderline Systolic BP',
        clinicalValue: '104 mmHg',
        normalRange: '110 - 130 mmHg',
        importancePercent: 16.5,
        impactDirection: 'ELEVATES_RISK',
      },
    ],
    clinicalRationale: 'ESP32 6-axis IMU detected rapid vertical deceleration followed by persistent disorientation motion pattern.',
  },
  'PT-105': {
    patientId: 'PT-105',
    patientName: 'David Chen',
    predictedCondition: 'Uncomplicated Post-Surgical Recovery',
    riskLevel: 'STABLE',
    confidence: 97.4,
    assignedDoctor: 'Dr. Sarah Lin, MD',
    department: 'Critical Care / ICU',
    analysisTimestamp: '2026-08-27 07:55:10 UTC',
    modelIdentifier: 'FastAPI Random Forest Clinical Risk v2.4 (Ensemble)',
    recommendedAction: 'Maintain standard 4-hour vital checks. Progress diet as tolerated, encourage early ambulation.',
    featureAttributions: [
      {
        feature: 'Normal SpO2',
        clinicalValue: '99 %',
        normalRange: '95 - 100 %',
        importancePercent: 35.0,
        impactDirection: 'PROTECTIVE',
      },
      {
        feature: 'Normal Heart Rate',
        clinicalValue: '68 BPM',
        normalRange: '60 - 100 BPM',
        importancePercent: 30.0,
        impactDirection: 'PROTECTIVE',
      },
      {
        feature: 'Normothermia',
        clinicalValue: '36.6 °C',
        normalRange: '36.5 - 37.5 °C',
        importancePercent: 20.0,
        impactDirection: 'PROTECTIVE',
      },
      {
        feature: 'Stable Blood Pressure',
        clinicalValue: '118/76 mmHg',
        normalRange: '100-130 / 60-85 mmHg',
        importancePercent: 15.0,
        impactDirection: 'PROTECTIVE',
      },
    ],
    clinicalRationale: 'All autonomic and sensor telemetry indicators reside safely within target non-critical physiological envelopes.',
  },
  'PT-106': {
    patientId: 'PT-106',
    patientName: 'Evelyn Brooks',
    predictedCondition: 'Hypertensive Crisis with Ventricular Ectopy',
    riskLevel: 'HIGH_RISK',
    confidence: 89.7,
    assignedDoctor: 'Dr. James Caldwell, MD',
    department: 'Cardiology',
    analysisTimestamp: '2026-08-27 08:00:35 UTC',
    modelIdentifier: 'FastAPI Random Forest Clinical Risk v2.4 (Ensemble)',
    recommendedAction: 'Titrate IV antihypertensives to target SBP < 140 mmHg within 1 hour; initiate continuous 5-lead telemetry surveillance.',
    featureAttributions: [
      {
        feature: 'Severe Systolic Hypertension',
        clinicalValue: '160 mmHg',
        normalRange: '100 - 130 mmHg',
        importancePercent: 38.0,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'Ventricular Ectopy on ECG',
        clinicalValue: 'PVCs detected (>6/min)',
        normalRange: 'None',
        importancePercent: 32.0,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'Tachypnea',
        clinicalValue: '24 breaths/min',
        normalRange: '12 - 20 bpm',
        importancePercent: 18.0,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'SpO2 Desaturation',
        clinicalValue: '92 %',
        normalRange: '95 - 100 %',
        importancePercent: 12.0,
        impactDirection: 'ELEVATES_RISK',
      },
    ],
    clinicalRationale: 'Significant afterload stress combined with myocardial electrical irritability indicating high risk of ischemic cardiac event.',
  },
  'PT-107': {
    patientId: 'PT-107',
    patientName: 'Samuel Okafor',
    predictedCondition: 'Resolving Soft Tissue Infection',
    riskLevel: 'STABLE',
    confidence: 96.1,
    assignedDoctor: 'Dr. Robert Sterling, MD',
    department: 'Emergency Medicine',
    analysisTimestamp: '2026-08-27 07:52:15 UTC',
    modelIdentifier: 'FastAPI Random Forest Clinical Risk v2.4 (Ensemble)',
    recommendedAction: 'Continue current IV antibiotics. Plan oral switch and discharge criteria assessment for tomorrow morning.',
    featureAttributions: [
      {
        feature: 'Normal SpO2',
        clinicalValue: '98 %',
        normalRange: '95 - 100 %',
        importancePercent: 30.0,
        impactDirection: 'PROTECTIVE',
      },
      {
        feature: 'Normal Heart Rate',
        clinicalValue: '72 BPM',
        normalRange: '60 - 100 BPM',
        importancePercent: 30.0,
        impactDirection: 'PROTECTIVE',
      },
      {
        feature: 'Normothermia',
        clinicalValue: '36.7 °C',
        normalRange: '36.5 - 37.5 °C',
        importancePercent: 25.0,
        impactDirection: 'PROTECTIVE',
      },
      {
        feature: 'Blood Pressure',
        clinicalValue: '124/80 mmHg',
        normalRange: '100-130 / 60-85 mmHg',
        importancePercent: 15.0,
        impactDirection: 'PROTECTIVE',
      },
    ],
    clinicalRationale: 'Vital signs completely stabilized within normal parameters over the past 18 hours.',
  },
  'PT-108': {
    patientId: 'PT-108',
    patientName: 'Beatrice Morales',
    predictedCondition: 'Acute Hypoxemic Respiratory Distress (Type I ARDS)',
    riskLevel: 'CRITICAL',
    confidence: 96.8,
    assignedDoctor: 'Dr. Maya Patel, MD',
    department: 'Pulmonology',
    analysisTimestamp: '2026-08-27 08:02:25 UTC',
    modelIdentifier: 'FastAPI Random Forest Clinical Risk v2.4 (Ensemble)',
    recommendedAction: 'CRITICAL ESCALATION: Prepare for non-invasive ventilation (NIV) or intubation, notify Rapid Response Team immediately, titrate FiO2.',
    featureAttributions: [
      {
        feature: 'Severe SpO2 Desaturation',
        clinicalValue: '86 %',
        normalRange: '95 - 100 %',
        importancePercent: 44.5,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'Severe Tachypnea',
        clinicalValue: '30 breaths/min',
        normalRange: '12 - 20 bpm',
        importancePercent: 26.0,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'Tachycardia',
        clinicalValue: '134 BPM',
        normalRange: '60 - 100 BPM',
        importancePercent: 18.5,
        impactDirection: 'ELEVATES_RISK',
      },
      {
        feature: 'Hyperpyrexia',
        clinicalValue: '38.7 °C',
        normalRange: '36.5 - 37.5 °C',
        importancePercent: 11.0,
        impactDirection: 'ELEVATES_RISK',
      },
    ],
    clinicalRationale: 'Rapid pulmonary gas-exchange breakdown with persistent hypoxemia failing supplemental high flow oxygen.',
  },
};

export const INITIAL_DETERIORATION_DATA: Record<string, DeteriorationData> = {
  'PT-101': {
    patientId: 'PT-101',
    patientName: 'Arthur Pendelton',
    deteriorationScore: 88,
    status: 'CRITICAL',
    lastCalculated: '2026-08-27 08:02:15 UTC',
    deteriorationVelocity: 'RAPID',
    baselineValues: {
      heartRate: 78,
      spO2: 97,
      temperature: 37.0,
      respRate: 16,
      bloodPressure: '120/78 mmHg',
    },
    currentValues: {
      heartRate: 126,
      spO2: 89,
      temperature: 39.2,
      respRate: 28,
      bloodPressure: '85/54 mmHg',
    },
    flaggedReasons: [
      'SpO2 decreasing rapidly: dropped from 97% to 89% (-8%)',
      'Heart rate increasing severely: accelerated from 78 to 126 BPM (+48 BPM)',
      'Temperature increasing sharply: spiked from 37.0°C to 39.2°C (+2.2°C)',
      'Abnormal values persisting sustained > 35 minutes',
      'Systolic blood pressure dropped below critical margin (< 90 mmHg)',
    ],
    historicalTrends: [
      { time: '02:00', heartRate: 78, spO2: 97, temperature: 37.0, respiratoryRate: 16, systolicBP: 120, diastolicBP: 78, deteriorationIndex: 12 },
      { time: '03:00', heartRate: 82, spO2: 96, temperature: 37.2, respiratoryRate: 17, systolicBP: 118, diastolicBP: 76, deteriorationIndex: 18 },
      { time: '04:00', heartRate: 88, spO2: 95, temperature: 37.6, respiratoryRate: 19, systolicBP: 112, diastolicBP: 72, deteriorationIndex: 32 },
      { time: '05:00', heartRate: 98, spO2: 94, temperature: 38.1, respiratoryRate: 22, systolicBP: 104, diastolicBP: 68, deteriorationIndex: 48 },
      { time: '06:00', heartRate: 108, spO2: 92, temperature: 38.6, respiratoryRate: 24, systolicBP: 96, diastolicBP: 62, deteriorationIndex: 68 },
      { time: '07:00', heartRate: 118, spO2: 91, temperature: 38.9, respiratoryRate: 26, systolicBP: 90, diastolicBP: 58, deteriorationIndex: 79 },
      { time: '07:30', heartRate: 122, spO2: 90, temperature: 39.1, respiratoryRate: 27, systolicBP: 88, diastolicBP: 56, deteriorationIndex: 84 },
      { time: '08:00', heartRate: 126, spO2: 89, temperature: 39.2, respiratoryRate: 28, systolicBP: 85, diastolicBP: 54, deteriorationIndex: 88 },
    ],
  },
  'PT-102': {
    patientId: 'PT-102',
    patientName: 'Elena Rostova',
    deteriorationScore: 68,
    status: 'DETERIORATING',
    lastCalculated: '2026-08-27 08:01:52 UTC',
    deteriorationVelocity: 'MODERATE',
    baselineValues: {
      heartRate: 72,
      spO2: 98,
      temperature: 36.8,
      respRate: 15,
      bloodPressure: '128/80 mmHg',
    },
    currentValues: {
      heartRate: 118,
      spO2: 92,
      temperature: 37.9,
      respRate: 22,
      bloodPressure: '145/92 mmHg',
    },
    flaggedReasons: [
      'Heart rate increasing: jumped from 72 to 118 BPM (+46 BPM)',
      'SpO2 decreasing: fell from 98% to 92% (-6%)',
      'ECG telemetry detecting paroxysmal Atrial Fibrillation',
      'Abnormal values persisting > 20 minutes',
    ],
    historicalTrends: [
      { time: '02:00', heartRate: 72, spO2: 98, temperature: 36.8, respiratoryRate: 15, systolicBP: 128, diastolicBP: 80, deteriorationIndex: 8 },
      { time: '03:00', heartRate: 74, spO2: 97, temperature: 36.9, respiratoryRate: 16, systolicBP: 126, diastolicBP: 82, deteriorationIndex: 12 },
      { time: '04:00', heartRate: 76, spO2: 97, temperature: 37.0, respiratoryRate: 16, systolicBP: 130, diastolicBP: 84, deteriorationIndex: 15 },
      { time: '05:00', heartRate: 85, spO2: 96, temperature: 37.2, respiratoryRate: 18, systolicBP: 134, diastolicBP: 86, deteriorationIndex: 28 },
      { time: '06:00', heartRate: 98, spO2: 95, temperature: 37.4, respiratoryRate: 19, systolicBP: 138, diastolicBP: 88, deteriorationIndex: 44 },
      { time: '07:00', heartRate: 112, spO2: 93, temperature: 37.7, respiratoryRate: 21, systolicBP: 142, diastolicBP: 90, deteriorationIndex: 59 },
      { time: '07:30', heartRate: 116, spO2: 92, temperature: 37.8, respiratoryRate: 22, systolicBP: 144, diastolicBP: 92, deteriorationIndex: 64 },
      { time: '08:00', heartRate: 118, spO2: 92, temperature: 37.9, respiratoryRate: 22, systolicBP: 145, diastolicBP: 92, deteriorationIndex: 68 },
    ],
  },
  'PT-103': {
    patientId: 'PT-103',
    patientName: 'Marcus Vance',
    deteriorationScore: 36,
    status: 'MONITORING',
    lastCalculated: '2026-08-27 07:59:15 UTC',
    deteriorationVelocity: 'STEADY',
    baselineValues: {
      heartRate: 80,
      spO2: 96,
      temperature: 36.9,
      respRate: 16,
      bloodPressure: '120/75 mmHg',
    },
    currentValues: {
      heartRate: 88,
      spO2: 94,
      temperature: 37.2,
      respRate: 20,
      bloodPressure: '122/78 mmHg',
    },
    flaggedReasons: [
      'SpO2 hovering below normal baseline (94% on 2L O2)',
      'Mild elevation in respiratory rate (20 breaths/min)',
    ],
    historicalTrends: [
      { time: '02:00', heartRate: 80, spO2: 96, temperature: 36.9, respiratoryRate: 16, systolicBP: 120, diastolicBP: 75, deteriorationIndex: 15 },
      { time: '03:00', heartRate: 82, spO2: 95, temperature: 37.0, respiratoryRate: 17, systolicBP: 122, diastolicBP: 76, deteriorationIndex: 20 },
      { time: '04:00', heartRate: 84, spO2: 95, temperature: 37.1, respiratoryRate: 18, systolicBP: 120, diastolicBP: 76, deteriorationIndex: 24 },
      { time: '05:00', heartRate: 86, spO2: 94, temperature: 37.1, respiratoryRate: 19, systolicBP: 124, diastolicBP: 78, deteriorationIndex: 30 },
      { time: '06:00', heartRate: 87, spO2: 94, temperature: 37.2, respiratoryRate: 19, systolicBP: 122, diastolicBP: 78, deteriorationIndex: 32 },
      { time: '07:00', heartRate: 88, spO2: 94, temperature: 37.2, respiratoryRate: 20, systolicBP: 122, diastolicBP: 78, deteriorationIndex: 36 },
      { time: '08:00', heartRate: 88, spO2: 94, temperature: 37.2, respiratoryRate: 20, systolicBP: 122, diastolicBP: 78, deteriorationIndex: 36 },
    ],
  },
  'PT-104': {
    patientId: 'PT-104',
    patientName: 'Clara Higgins',
    deteriorationScore: 62,
    status: 'MONITORING',
    lastCalculated: '2026-08-27 08:02:02 UTC',
    deteriorationVelocity: 'RAPID',
    baselineValues: {
      heartRate: 70,
      spO2: 97,
      temperature: 36.7,
      respRate: 15,
      bloodPressure: '115/70 mmHg',
    },
    currentValues: {
      heartRate: 76,
      spO2: 96,
      temperature: 36.8,
      respRate: 17,
      bloodPressure: '104/66 mmHg',
    },
    flaggedReasons: [
      'Fall detection algorithm triggered: 3.4G acceleration anomaly',
      'Motion status indicated sudden agitation/bed displacement',
      'Blood pressure decreased below resting baseline (104/66 mmHg)',
    ],
    historicalTrends: [
      { time: '02:00', heartRate: 70, spO2: 97, temperature: 36.7, respiratoryRate: 15, systolicBP: 115, diastolicBP: 70, deteriorationIndex: 10 },
      { time: '04:00', heartRate: 69, spO2: 97, temperature: 36.7, respiratoryRate: 15, systolicBP: 114, diastolicBP: 70, deteriorationIndex: 12 },
      { time: '06:00', heartRate: 71, spO2: 96, temperature: 36.8, respiratoryRate: 16, systolicBP: 112, diastolicBP: 68, deteriorationIndex: 18 },
      { time: '07:30', heartRate: 72, spO2: 96, temperature: 36.8, respiratoryRate: 16, systolicBP: 110, diastolicBP: 68, deteriorationIndex: 22 },
      { time: '08:00', heartRate: 76, spO2: 96, temperature: 36.8, respiratoryRate: 17, systolicBP: 104, diastolicBP: 66, deteriorationIndex: 62 },
    ],
  },
  'PT-105': {
    patientId: 'PT-105',
    patientName: 'David Chen',
    deteriorationScore: 8,
    status: 'STABLE',
    lastCalculated: '2026-08-27 07:55:10 UTC',
    deteriorationVelocity: 'STEADY',
    baselineValues: {
      heartRate: 66,
      spO2: 99,
      temperature: 36.5,
      respRate: 14,
      bloodPressure: '116/74 mmHg',
    },
    currentValues: {
      heartRate: 68,
      spO2: 99,
      temperature: 36.6,
      respRate: 14,
      bloodPressure: '118/76 mmHg',
    },
    flaggedReasons: [],
    historicalTrends: [
      { time: '02:00', heartRate: 65, spO2: 99, temperature: 36.5, respiratoryRate: 14, systolicBP: 116, diastolicBP: 74, deteriorationIndex: 7 },
      { time: '04:00', heartRate: 66, spO2: 99, temperature: 36.5, respiratoryRate: 14, systolicBP: 116, diastolicBP: 74, deteriorationIndex: 8 },
      { time: '06:00', heartRate: 67, spO2: 99, temperature: 36.6, respiratoryRate: 14, systolicBP: 117, diastolicBP: 75, deteriorationIndex: 8 },
      { time: '08:00', heartRate: 68, spO2: 99, temperature: 36.6, respiratoryRate: 14, systolicBP: 118, diastolicBP: 76, deteriorationIndex: 8 },
    ],
  },
  'PT-106': {
    patientId: 'PT-106',
    patientName: 'Evelyn Brooks',
    deteriorationScore: 72,
    status: 'DETERIORATING',
    lastCalculated: '2026-08-27 08:00:35 UTC',
    deteriorationVelocity: 'MODERATE',
    baselineValues: {
      heartRate: 75,
      spO2: 96,
      temperature: 36.8,
      respRate: 16,
      bloodPressure: '135/85 mmHg',
    },
    currentValues: {
      heartRate: 105,
      spO2: 92,
      temperature: 37.4,
      respRate: 24,
      bloodPressure: '160/98 mmHg',
    },
    flaggedReasons: [
      'Systolic blood pressure increasing to stage 2 urgency level (160 mmHg)',
      'Heart rate increasing from 75 to 105 BPM (+30 BPM)',
      'SpO2 decreasing from 96% to 92% (-4%)',
      'Abnormal ventricular ectopy pattern persisting > 15 mins',
    ],
    historicalTrends: [
      { time: '02:00', heartRate: 75, spO2: 96, temperature: 36.8, respiratoryRate: 16, systolicBP: 135, diastolicBP: 85, deteriorationIndex: 14 },
      { time: '04:00', heartRate: 80, spO2: 95, temperature: 36.9, respiratoryRate: 17, systolicBP: 140, diastolicBP: 88, deteriorationIndex: 26 },
      { time: '06:00', heartRate: 92, spO2: 94, temperature: 37.1, respiratoryRate: 20, systolicBP: 148, diastolicBP: 92, deteriorationIndex: 48 },
      { time: '07:30', heartRate: 100, spO2: 93, temperature: 37.3, respiratoryRate: 22, systolicBP: 156, diastolicBP: 96, deteriorationIndex: 65 },
      { time: '08:00', heartRate: 105, spO2: 92, temperature: 37.4, respiratoryRate: 24, systolicBP: 160, diastolicBP: 98, deteriorationIndex: 72 },
    ],
  },
  'PT-107': {
    patientId: 'PT-107',
    patientName: 'Samuel Okafor',
    deteriorationScore: 11,
    status: 'STABLE',
    lastCalculated: '2026-08-27 07:52:15 UTC',
    deteriorationVelocity: 'STEADY',
    baselineValues: {
      heartRate: 70,
      spO2: 98,
      temperature: 36.7,
      respRate: 15,
      bloodPressure: '122/80 mmHg',
    },
    currentValues: {
      heartRate: 72,
      spO2: 98,
      temperature: 36.7,
      respRate: 15,
      bloodPressure: '124/80 mmHg',
    },
    flaggedReasons: [],
    historicalTrends: [
      { time: '02:00', heartRate: 71, spO2: 98, temperature: 36.8, respiratoryRate: 15, systolicBP: 122, diastolicBP: 80, deteriorationIndex: 12 },
      { time: '04:00', heartRate: 70, spO2: 98, temperature: 36.7, respiratoryRate: 15, systolicBP: 123, diastolicBP: 80, deteriorationIndex: 11 },
      { time: '06:00', heartRate: 72, spO2: 98, temperature: 36.7, respiratoryRate: 15, systolicBP: 124, diastolicBP: 80, deteriorationIndex: 11 },
      { time: '08:00', heartRate: 72, spO2: 98, temperature: 36.7, respiratoryRate: 15, systolicBP: 124, diastolicBP: 80, deteriorationIndex: 11 },
    ],
  },
  'PT-108': {
    patientId: 'PT-108',
    patientName: 'Beatrice Morales',
    deteriorationScore: 92,
    status: 'CRITICAL',
    lastCalculated: '2026-08-27 08:02:25 UTC',
    deteriorationVelocity: 'RAPID',
    baselineValues: {
      heartRate: 84,
      spO2: 95,
      temperature: 37.2,
      respRate: 18,
      bloodPressure: '120/75 mmHg',
    },
    currentValues: {
      heartRate: 134,
      spO2: 86,
      temperature: 38.7,
      respRate: 30,
      bloodPressure: '90/60 mmHg',
    },
    flaggedReasons: [
      'Critical SpO2 drop: dropped precipitously from 95% to 86% (-9%)',
      'Severe respiratory rate acceleration: 30 breaths/min (Tachypnea)',
      'Severe sinus tachycardia: 134 BPM (+50 BPM above baseline)',
      'Hypotensive trending: SBP dropped to 90 mmHg',
      'Abnormal values persisting > 40 minutes',
    ],
    historicalTrends: [
      { time: '02:00', heartRate: 84, spO2: 95, temperature: 37.2, respiratoryRate: 18, systolicBP: 120, diastolicBP: 75, deteriorationIndex: 20 },
      { time: '04:00', heartRate: 94, spO2: 93, temperature: 37.6, respiratoryRate: 21, systolicBP: 114, diastolicBP: 72, deteriorationIndex: 40 },
      { time: '06:00', heartRate: 110, spO2: 90, temperature: 38.1, respiratoryRate: 25, systolicBP: 104, diastolicBP: 66, deteriorationIndex: 68 },
      { time: '07:30', heartRate: 125, spO2: 88, temperature: 38.5, respiratoryRate: 28, systolicBP: 94, diastolicBP: 62, deteriorationIndex: 85 },
      { time: '08:00', heartRate: 134, spO2: 86, temperature: 38.7, respiratoryRate: 30, systolicBP: 90, diastolicBP: 60, deteriorationIndex: 92 },
    ],
  },
};

export const INITIAL_EXPLAINABLE_RISK: Record<string, ExplainableRiskData> = {
  'PT-101': {
    patientId: 'PT-101',
    patientName: 'Arthur Pendelton',
    riskLevel: 'CRITICAL',
    deteriorationScore: 88,
    abnormalDurationMinutes: 45,
    backendEndpoint: 'GET /api/v1/ai/explain/PT-101',
    reasons: [
      'SpO2 dropped from 97% to 89% (-8% below safety limit)',
      'Heart rate increased from 78 to 126 BPM (+48 BPM tachycardia)',
      'Body temperature spiked from 37.0°C to 39.2°C (+2.2°C febrile crisis)',
      'Systolic blood pressure decreased from 120 to 85 mmHg (Hypotension)',
      'Abnormal multi-vital deterioration pattern persisted continuously for 45 minutes',
      'Random Forest ML model classified patient as CRITICAL with 94.6% confidence',
    ],
    factors: [
      {
        parameter: 'SpO2 (Oxygen Saturation)',
        baseline: '97 %',
        current: '89 %',
        delta: '-8 %',
        severity: 'CRITICAL',
        description: 'Persistent arterial hypoxemia exceeding safe physiological compensatory limits.',
      },
      {
        parameter: 'Heart Rate',
        baseline: '78 BPM',
        current: '126 BPM',
        delta: '+48 BPM',
        severity: 'CRITICAL',
        description: 'Marked sinus tachycardia compensating for decreased systemic vascular resistance.',
      },
      {
        parameter: 'Body Temperature',
        baseline: '37.0 °C',
        current: '39.2 °C',
        delta: '+2.2 °C',
        severity: 'CRITICAL',
        description: 'Severe febrile response consistent with systemic infectious escalation.',
      },
      {
        parameter: 'Systolic Blood Pressure',
        baseline: '120 mmHg',
        current: '85 mmHg',
        delta: '-35 mmHg',
        severity: 'CRITICAL',
        description: 'Refractory hypotension meeting clinical criteria for early septic shock.',
      },
      {
        parameter: 'Respiratory Rate',
        baseline: '16 bpm',
        current: '28 bpm',
        delta: '+12 bpm',
        severity: 'MODERATE',
        description: 'Tachypneic compensation for metabolic acid-base disturbance.',
      },
    ],
    aiAttributionNotes: 'Feature importance generated by Random Forest clinical classifier. High temperature elevation and SpO2 delta represent 62.7% of total risk weight.',
  },
  'PT-102': {
    patientId: 'PT-102',
    patientName: 'Elena Rostova',
    riskLevel: 'HIGH_RISK',
    deteriorationScore: 68,
    abnormalDurationMinutes: 25,
    backendEndpoint: 'GET /api/v1/ai/explain/PT-102',
    reasons: [
      'Heart rate increased from 72 to 118 BPM (+46 BPM tachyarrhythmia)',
      'SpO2 dropped from 98% to 92% (-6% desaturation)',
      'ECG telemetry pattern shifted from Normal Sinus to Atrial Fibrillation',
      'Abnormal arrhythmia pattern persisted > 25 minutes',
      'Random Forest model flagged for acute post-CABG atrial arrhythmia',
    ],
    factors: [
      {
        parameter: 'Heart Rate',
        baseline: '72 BPM',
        current: '118 BPM',
        delta: '+46 BPM',
        severity: 'CRITICAL',
        description: 'Sudden tachycardia with irregular R-R intervals on Lead II telemetry.',
      },
      {
        parameter: 'SpO2 (Oxygen Saturation)',
        baseline: '98 %',
        current: '92 %',
        delta: '-6 %',
        severity: 'MODERATE',
        description: 'Moderate desaturation due to reduced cardiac output in AFib with RVR.',
      },
      {
        parameter: 'Systolic Blood Pressure',
        baseline: '128 mmHg',
        current: '145 mmHg',
        delta: '+17 mmHg',
        severity: 'MODERATE',
        description: 'Sympathetic hyperactivity during acute arrhythmic episode.',
      },
    ],
    aiAttributionNotes: 'Primary risk vector driven by sudden HR velocity shift and ECG rhythm divergence (68.4% attribution).',
  },
  'PT-104': {
    patientId: 'PT-104',
    patientName: 'Clara Higgins',
    riskLevel: 'HIGH_RISK',
    deteriorationScore: 62,
    abnormalDurationMinutes: 8,
    backendEndpoint: 'GET /api/v1/ai/explain/PT-104',
    reasons: [
      'ESP32 6-axis IoT sensor detected sudden vertical impact acceleration (3.4G)',
      'Motion pattern switched from resting to agitated disorientation',
      'Systolic blood pressure dropped from 115 to 104 mmHg',
      'AI algorithm classified event as HIGH_RISK patient fall incident',
    ],
    factors: [
      {
        parameter: 'IoT Fall Impact Vector',
        baseline: '1.0 G (Gravity)',
        current: '3.4 G (Peak)',
        delta: '+2.4 G',
        severity: 'CRITICAL',
        description: 'Instantaneous deceleration signature matching unassisted bedside fall.',
      },
      {
        parameter: 'Motion State',
        baseline: 'Resting',
        current: 'Agitated',
        delta: 'State Shift',
        severity: 'MODERATE',
        description: 'Disorientation motion telemetry detected immediately post-impact.',
      },
    ],
    aiAttributionNotes: 'Event-triggered rule and Random Forest combined classification for immediate clinical staff intervention.',
  },
  'PT-106': {
    patientId: 'PT-106',
    patientName: 'Evelyn Brooks',
    riskLevel: 'HIGH_RISK',
    deteriorationScore: 72,
    abnormalDurationMinutes: 30,
    backendEndpoint: 'GET /api/v1/ai/explain/PT-106',
    reasons: [
      'Systolic blood pressure surged from 135 to 160 mmHg (+25 mmHg)',
      'Heart rate accelerated from 75 to 105 BPM (+30 BPM)',
      'SpO2 dropped from 96% to 92% (-4%)',
      'Lead II ECG telemetry detected frequent premature ventricular contractions',
      'AI model flagged acute hypertensive urgency and potential coronary ischemia',
    ],
    factors: [
      {
        parameter: 'Systolic Blood Pressure',
        baseline: '135 mmHg',
        current: '160 mmHg',
        delta: '+25 mmHg',
        severity: 'CRITICAL',
        description: 'Severe afterload elevation increasing myocardial oxygen demand.',
      },
      {
        parameter: 'Heart Rate',
        baseline: '75 BPM',
        current: '105 BPM',
        delta: '+30 BPM',
        severity: 'MODERATE',
        description: 'Sinus tachycardia with ectopic ventricular complexes.',
      },
      {
        parameter: 'SpO2',
        baseline: '96 %',
        current: '92 %',
        delta: '-4 %',
        severity: 'MODERATE',
        description: 'Early pulmonary congestion / ventilation-perfusion mismatch.',
      },
    ],
    aiAttributionNotes: 'Blood pressure escalation and ventricular ectopy represent 70% of feature weight.',
  },
  'PT-108': {
    patientId: 'PT-108',
    patientName: 'Beatrice Morales',
    riskLevel: 'CRITICAL',
    deteriorationScore: 92,
    abnormalDurationMinutes: 40,
    backendEndpoint: 'GET /api/v1/ai/explain/PT-108',
    reasons: [
      'SpO2 dropped precipitously from 95% to 86% (-9% severe hypoxemia)',
      'Respiratory rate surged from 18 to 30 breaths/min (+12 bpm severe tachypnea)',
      'Heart rate increased from 84 to 134 BPM (+50 BPM severe tachycardia)',
      'Temperature elevated to 38.7°C with worsening oxygenation ratio',
      'Abnormal hypoxic pattern persisted for 40 minutes despite 6L O2',
      'AI Random Forest classified as CRITICAL (ARDS / Impending Respiratory Failure)',
    ],
    factors: [
      {
        parameter: 'SpO2 (Oxygen Saturation)',
        baseline: '95 %',
        current: '86 %',
        delta: '-9 %',
        severity: 'CRITICAL',
        description: 'Profound hypoxemic respiratory failure requiring immediate advanced airway support.',
      },
      {
        parameter: 'Respiratory Rate',
        baseline: '18 bpm',
        current: '30 bpm',
        delta: '+12 bpm',
        severity: 'CRITICAL',
        description: 'Severe tachypneic distress with impending diaphragmatic exhaustion.',
      },
      {
        parameter: 'Heart Rate',
        baseline: '84 BPM',
        current: '134 BPM',
        delta: '+50 BPM',
        severity: 'CRITICAL',
        description: 'Severe tachycardia driven by extreme hypoxic drive and fever.',
      },
    ],
    aiAttributionNotes: 'Severe oxygenation decline and tachypnea constitute 70.5% of total predictive model weighting.',
  },
};

export const INITIAL_CLINICAL_ALERTS: ClinicalAlert[] = [
  {
    id: 'ALT-9041',
    patientId: 'PT-101',
    patientName: 'Arthur Pendelton',
    ward: 'ICU Unit A',
    bed: 'Bed 04',
    predictedCondition: 'Septic Shock / Hemodynamic Collapse',
    riskLevel: 'CRITICAL',
    deteriorationScore: 88,
    alertReason: 'SpO2 89% (dropped -8%), HR 126 BPM, Temp 39.2°C, SBP 85 mmHg persisting > 35m',
    assignedDoctor: 'Dr. Sarah Lin, MD',
    doctorId: 'DOC-01',
    emailStatus: 'SENT',
    ackStatus: 'PENDING',
    timestamp: '2026-08-27 08:02:15 UTC',
  },
  {
    id: 'ALT-9040',
    patientId: 'PT-108',
    patientName: 'Beatrice Morales',
    ward: 'ICU Unit B',
    bed: 'Bed 01',
    predictedCondition: 'Acute Hypoxemic Respiratory Distress (ARDS)',
    riskLevel: 'CRITICAL',
    deteriorationScore: 92,
    alertReason: 'SpO2 86%, Resp Rate 30 bpm, HR 134 BPM, failing supplemental high flow O2',
    assignedDoctor: 'Dr. Maya Patel, MD',
    doctorId: 'DOC-03',
    emailStatus: 'SENT',
    ackStatus: 'PENDING',
    timestamp: '2026-08-27 08:01:10 UTC',
  },
  {
    id: 'ALT-9039',
    patientId: 'PT-104',
    patientName: 'Clara Higgins',
    ward: 'Geriatric Med Ward',
    bed: 'Bed 19',
    predictedCondition: 'Acute Motion / Fall Impact Event',
    riskLevel: 'HIGH_RISK',
    deteriorationScore: 62,
    alertReason: 'ESP32 IoT sensor triggered 3.4G impact alert with subsequent patient agitation',
    assignedDoctor: 'Dr. Robert Sterling, MD',
    doctorId: 'DOC-04',
    emailStatus: 'SENT',
    ackStatus: 'PENDING',
    timestamp: '2026-08-27 07:58:30 UTC',
  },
  {
    id: 'ALT-9038',
    patientId: 'PT-106',
    patientName: 'Evelyn Brooks',
    ward: 'Cardiology Telemetry',
    bed: 'Bed 08',
    predictedCondition: 'Hypertensive Crisis with Ventricular Ectopy',
    riskLevel: 'HIGH_RISK',
    deteriorationScore: 72,
    alertReason: 'SBP 160 mmHg, HR 105 BPM, PVCs detected on Lead II ECG telemetry',
    assignedDoctor: 'Dr. James Caldwell, MD',
    doctorId: 'DOC-02',
    emailStatus: 'SENT',
    ackStatus: 'COOLDOWN',
    timestamp: '2026-08-27 07:45:12 UTC',
  },
  {
    id: 'ALT-9037',
    patientId: 'PT-102',
    patientName: 'Elena Rostova',
    ward: 'Stepdown Ward C',
    bed: 'Bed 12',
    predictedCondition: 'Post-Op Atrial Fibrillation with RVR',
    riskLevel: 'HIGH_RISK',
    deteriorationScore: 68,
    alertReason: 'HR 118 BPM AFib onset, SpO2 92% desaturation trend',
    assignedDoctor: 'Dr. James Caldwell, MD',
    doctorId: 'DOC-02',
    emailStatus: 'SENT',
    ackStatus: 'ACKNOWLEDGED',
    timestamp: '2026-08-27 07:15:00 UTC',
    acknowledgedBy: 'Dr. James Caldwell, MD',
    acknowledgedAt: '2026-08-27 07:22:10 UTC',
    clinicalActionNote: 'Attending at bedside. Ordered stat 12-lead ECG, IV metoprolol 5mg administered.',
  },
  {
    id: 'ALT-9036',
    patientId: 'PT-103',
    patientName: 'Marcus Vance',
    ward: 'Pulmonary Ward B',
    bed: 'Bed 07',
    predictedCondition: 'Borderline Hypoxemia',
    riskLevel: 'MONITORING',
    deteriorationScore: 36,
    alertReason: 'SpO2 94% on ambient air before nasal cannula titration',
    assignedDoctor: 'Dr. Maya Patel, MD',
    doctorId: 'DOC-03',
    emailStatus: 'ACKNOWLEDGED',
    ackStatus: 'ACKNOWLEDGED',
    timestamp: '2026-08-27 06:40:00 UTC',
    acknowledgedBy: 'Dr. Maya Patel, MD',
    acknowledgedAt: '2026-08-27 06:50:18 UTC',
    clinicalActionNote: 'Nasal cannula 2L/min started. Target SpO2 maintained >94%.',
  },
];

export const INITIAL_OVERVIEW_METRICS: OverviewMetrics = {
  totalPatients: 8,
  stablePatients: 2,
  monitoringRequired: 2,
  highRiskPatients: 2,
  criticalPatients: 2,
  activeAlerts: 4,
  acknowledgedAlertsToday: 14,
  iotNodesOnline: 8,
  totalIotNodes: 8,
};
